apiVersion: v1
kind: Service
metadata:
  name: doctor-mysql
spec:
  selector:
    app: doctor-mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-backend
spec:
  selector:
    app: doctor-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
  type: {{ .Values.backend.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-frontend
spec:
  selector:
    app: doctor-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
  type: {{ .Values.frontend.service.type }}