# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-frontend
  template:
    metadata:
      labels:
        app: doctor-frontend
    spec:
      containers:
      - name: doctor-frontend
        image: mah127/doctor-reservation-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-frontend
spec:
  selector:
    app: doctor-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer